@link = http://localhost:5001/api/books
@link2 = http://localhost:5001/api/students

GET http://localhost:5001/api/books/issue/logs/31 HTTP/1.1
###
put {{link}}/put/26
Content-Type: application/json

{
       "title": "r",
    "author": "granger",
    "category": "electrical dept.",
    "isbn":"92598745823645",
    "total_copies": 10,
    "available_copies": 4,
    "price":10.7
}
###
DELETE {{link2}}/21 HTTP/1.1

###
POST {{link}}   
Content-Type: application/json

{
    "student_id":1
}
###

###
GET {{link}}/issue/logs/1
###
GET {{link}}/issue/logs/book/23
###
GET {{link2}}/28
###

GET {{link}}/issue/log
###
POST {{link2}}/
Content-Type: application/json

{
    "name": "iw0329",
    "roll_number": "230987",
    "department": "CSE",
    "semester": 6,
    "phone": 1231344234,
    "email": "uakdfn@example.com"
}
###

GET {{link2}}/return/:23
###

# GET {{link}} HTTP/1.1
GET {{link2}}/all
###

DELETE {{link}}/17
###
GET {{link}} 
###
GET {{link}}/all
###
put {{link}}/21
Content-Type: application/json

{ 
    "title": "r",
    "author": "granger",
    "category": "electrical dept.",
    "isbn":"92598743t5823645",
    "total_copies": 10,
    "available_copies": 4,
    "price":10.7
}

###

GET {{link}}/data HTTP/1.1
###